//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoopsU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HoopsUDBEntities : DbContext
    {
        public HoopsUDBEntities()
            : base("name=HoopsUDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCourt> tblCourts { get; set; }
        public virtual DbSet<tblFavorite> tblFavorites { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    
        public virtual int sprAddUser(string fldUsername, string fldUserPassword, string fldUserFirstName, string fldUserLastName, Nullable<bool> fldUserGender, string fldUserAddress, string fldUserEmailAddress)
        {
            var fldUsernameParameter = fldUsername != null ?
                new ObjectParameter("fldUsername", fldUsername) :
                new ObjectParameter("fldUsername", typeof(string));
    
            var fldUserPasswordParameter = fldUserPassword != null ?
                new ObjectParameter("fldUserPassword", fldUserPassword) :
                new ObjectParameter("fldUserPassword", typeof(string));
    
            var fldUserFirstNameParameter = fldUserFirstName != null ?
                new ObjectParameter("fldUserFirstName", fldUserFirstName) :
                new ObjectParameter("fldUserFirstName", typeof(string));
    
            var fldUserLastNameParameter = fldUserLastName != null ?
                new ObjectParameter("fldUserLastName", fldUserLastName) :
                new ObjectParameter("fldUserLastName", typeof(string));
    
            var fldUserGenderParameter = fldUserGender.HasValue ?
                new ObjectParameter("fldUserGender", fldUserGender) :
                new ObjectParameter("fldUserGender", typeof(bool));
    
            var fldUserAddressParameter = fldUserAddress != null ?
                new ObjectParameter("fldUserAddress", fldUserAddress) :
                new ObjectParameter("fldUserAddress", typeof(string));
    
            var fldUserEmailAddressParameter = fldUserEmailAddress != null ?
                new ObjectParameter("fldUserEmailAddress", fldUserEmailAddress) :
                new ObjectParameter("fldUserEmailAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sprAddUser", fldUsernameParameter, fldUserPasswordParameter, fldUserFirstNameParameter, fldUserLastNameParameter, fldUserGenderParameter, fldUserAddressParameter, fldUserEmailAddressParameter);
        }
    
        public virtual ObjectResult<sprGetAllCourts_Result> sprGetAllCourts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sprGetAllCourts_Result>("sprGetAllCourts");
        }
    
        public virtual ObjectResult<sprGetCourtsByZone_Result> sprGetCourtsByZone(string fldCourtZone)
        {
            var fldCourtZoneParameter = fldCourtZone != null ?
                new ObjectParameter("fldCourtZone", fldCourtZone) :
                new ObjectParameter("fldCourtZone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sprGetCourtsByZone_Result>("sprGetCourtsByZone", fldCourtZoneParameter);
        }
    
        public virtual ObjectResult<string> sprGetFavoritesByUsername(string fldUsername)
        {
            var fldUsernameParameter = fldUsername != null ?
                new ObjectParameter("fldUsername", fldUsername) :
                new ObjectParameter("fldUsername", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sprGetFavoritesByUsername", fldUsernameParameter);
        }
    }
}
