//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoopsU
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCourt()
        {
            this.tblFavorites = new HashSet<tblFavorite>();
        }
    
        public int fldCourtID { get; set; }
        public string fldCourtName { get; set; }
        public int fldCourtCapacity { get; set; }
        public bool fldCourtFullSize { get; set; }
        public string fldCourtAddress { get; set; }
        public bool fldCourtParkingAvailable { get; set; }
        public string fldCourtZone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavorite> tblFavorites { get; set; }
    }
}
