//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoopsU
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFavorite
    {
        public int fldFavoriteID { get; set; }
        public int fldUser_ID { get; set; }
        public int fldCourt_ID { get; set; }
    
        public virtual tblCourt tblCourt { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
