//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoopsU
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblFavorites = new HashSet<tblFavorite>();
        }
    
        public int fldUserID { get; set; }
        public string fldUsername { get; set; }
        public string fldUserPassword { get; set; }
        public string fldUserFirstName { get; set; }
        public string fldUserLastName { get; set; }
        public bool fldUserGender { get; set; }
        public string fldUserAddress { get; set; }
        public string fldUserEmailAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavorite> tblFavorites { get; set; }
    }
}
